version: '3.8'

services:
  # Database Service
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      # Override DATABASE_URL to use service name instead of localhost
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase?schema=public"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    env_file:
      - ./frontend/.env
    environment:
      # Override backend URL to use service name instead of localhost
      VITE_BE_URL: "http://backend:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
